import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Link from 'next/link'
import { Amplify } from 'aws-amplify'
import config from '../aws-exports'
import Head from 'next/head'
Amplify.configure({ ...config, ssr: true })

export default function App({ Component, pageProps }: AppProps) {



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <nav className='bg-red-300'>
          <Link href="/">
            <span className='bg-green-300'>Home</span>
          </Link>
          <Link href="/protected">
            <span className='bg-orange-300'>Protected</span>
          </Link>
          <Link href="/protected-client-route">
            <span className=''>Protected client route</span>
          </Link>
        </nav>
      <Component {...pageProps} />
      </div>
    </>
  )
}

// const linkStyle = css`
//   margin-right: 20px;
//   cursor: pointer;
// `

// const navStyle = css`
//   display: flex;
// `
