import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
// aws services
import { Amplify } from 'aws-amplify'
import { Auth } from '@aws-amplify/auth'
import config from '../aws-exports'
// context
import { useState } from 'react'
import AuthContext from '../contexts/authContext'
import AppContext, { AppInfo } from '../contexts/appContext'


import '@fortawesome/fontawesome-svg-core/styles.css'
import NavBar from '../ui-components/navBar'


Amplify.configure({ ...config, ssr: true })

const appInfo = new (AppInfo)


/*
Open-Meteo api for weather info
https://api.open-meteo.com/v1/forecast?
latitude=36.03
&longitude=-95.83
&hourly=temperature_2m,apparent_temperature,precipitation,weathercode
&current_weather=true
&temperature_unit=fahrenheit
&windspeed_unit=mph
&timezone=America%2FChicago

we need from the device:
device geolocation
speed unit, mph, kmph
tiemzone info
*/
export default function App({ Component, pageProps }: AppProps) {
  const [user, setUser] = useState(null)
  const [appContext, setAppContext] = useState(appInfo)
  const router = useRouter()

  // console.log('APP USER', user)
  // console.log('APP CONTEXT', appContext)
  // probably need to set the context provider here, along with the ability to zero out values on signout

  return (
    <>
      <Head>
        <title>GarMint</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/mintLeaf.png" />
        {/* <link rel="stylesheet" type="text/css" href="//use.fontawesome.com/releases/v5.7.2/css/all.css" /> */}
      </Head>
      {user && (
        <NavBar />
        )}
      <AuthContext.Provider value={{user, setUser}}>
        <AppContext.Provider value={{appContext, setAppContext}}>
          <Component {...pageProps} />
        </AppContext.Provider>
      </AuthContext.Provider>
    </>
  )
}
